/*
 * File: app/view/LoginForm.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LoginForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.loginform',

    config: {
        title: '登录',
        id: 'LoginFormID',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: '  系统登录  '
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'loginSettingBtn',
                        ui: 'confirm',
                        text: '设置'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'loginLoginBtn',
                        ui: 'confirm',
                        text: '登录'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                defaults: 'labelAlign: \'left\',\n				labelWidth: \'40%\',\n				required: false,\n				useClearIcon: true,\n				autoCapitalize : false',
                instructions: '请选择登录方式，输入手机号码或Email地址和密码后，点击“登录"按钮。如果您是第一次使用本系统，请点击”设置“按钮',
                title: '登录帐号',
                items: [
                    {
                        xtype: 'selectfield',
                        label: '登录方式',
                        name: 'loginWay',
                        options: [
                            {
                                text: '手机号码',
                                value: 'mobilePhone'
                            },
                            {
                                text: 'Email',
                                value: 'email'
                            }
                        ]
                    },
                    {
                        xtype: 'numberfield',
                        itemId: 'mobilePhone',
                        label: '手机号码',
                        name: 'mobilePhone'
                    },
                    {
                        xtype: 'emailfield',
                        hidden: true,
                        itemId: 'email',
                        label: 'Email',
                        name: 'email',
                        placeHolder: 'email@example.com'
                    },
                    {
                        xtype: 'passwordfield',
                        itemId: 'passwd',
                        label: '密码',
                        name: 'passwd'
                    }
                ]
            }
        ]
    }

});