/*
 * File: app/view/mainView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.mainView', {
    extend: 'Ext.Panel',
    alias: 'widget.mainView',

    config: {
        title: '供销超市',
        id: 'MainListID',
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'dataview',
                flex: 1,
                id: 'MainListList',
                itemId: 'mydataview2',
                ui: 'light',
                inline: true,
                itemTpl: [
                    '<div class="extension">',
                    '	<div class="icon"><img src="{icon}" /></div>',
                    '	<div class="name">{name}</div>',
                    '</div>'
                ],
                store: 'extensionStoreID',
                useComponents: false
            }
        ]
    }

});