/*
 * File: app/view/productView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.productView', {
    extend: 'Ext.Panel',

    config: {
        fullscreen: true,
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'nestedlist',
                flex: 1,
                itemId: 'productList',
                ui: 'light',
                scrollable: 'vertical',
                detailCard: {
                    xclass: 'MyApp.view.productDetailView'
                },
                displayField: 'product_name',
                store: 'productStoreID',
                toolbar: {
                    xtype: 'titlebar',
                    hidden: true
                }
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'selectProductCancelBtn',
                        text: '取消'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        hidden: false,
                        id: 'btnBuyID',
                        ui: 'confirm',
                        text: '购买'
                    }
                ]
            }
        ]
    }

});