/*
 * File: app/view/productDetailView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.productDetailView', {
    extend: 'Ext.form.Panel',

    config: {
        id: 'productDetailViewID',
        items: [
            {
                xtype: 'fieldset',
                title: '商品信息',
                items: [
                    {
                        xtype: 'textfield',
                        label: '名称',
                        name: 'productName',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        label: '编号',
                        name: 'productSKU',
                        readOnly: true
                    },
                    {
                        xtype: 'numberfield',
                        label: '价格',
                        name: 'productSalePrice',
                        readOnly: true
                    }
                ]
            },
            {
                xtype: 'spinnerfield',
                label: '购买数量',
                labelWidth: '40%',
                name: 'fsBuyCount',
                required: true,
                defaultValue: 5,
                increment: 1
            },
            {
                xtype: 'textfield',
                label: '小计',
                name: 'txtSubTotal'
            }
        ]
    }

});