/*
 * File: app/view/settingView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.settingView', {
    extend: 'Ext.Panel',
    alias: 'widget.settingView',

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'settingSaveBtn',
                        text: '保存'
                    },
                    {
                        xtype: 'button',
                        itemId: 'settingCancelBtn',
                        text: '取消'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: '服务器设置',
                items: [
                    {
                        xtype: 'textfield',
                        label: '地址：'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: '登录配置',
                items: [
                    {
                        xtype: 'togglefield',
                        label: '记住密码'
                    }
                ]
            }
        ]
    }

});