/*
 * File: app/model/productModel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.productModel', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'product_sku',
                type: 'string'
            },
            {
                name: 'product_name',
                type: 'string'
            },
            {
                name: 'product_price',
                type: 'float'
            },
            {
                name: 'product_img',
                type: 'string'
            },
            {
                name: 'weigth_unit_display'
            }
        ]
    }
});