/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({

});

Ext.application({
    models: [
        'extensionModel',
        'systemVarModel',
        'productModel',
        'orderDetailModel'
    ],
    stores: [
        'extensionStore',
        'productStore',
        'orderDetailStore'
    ],
    views: [
        'executeView',
        'LoginForm',
        'mainView',
        'settingView',
        'productView',
        'productDetailView',
        'shoppingCartView'
    ],
    controllers: [
        'settingController',
        'mainListController',
        'loginController',
        'webServiceController',
        'productController',
        'orderController'
    ],
    icon: 'data/images/icon.png',
    name: 'MyApp',
    startupImage: {
        '320x460': 'data/images/phone_startup.png',
        '768x1004': 'data/images/table_startup.png'
    },

    launch: function() {
        loginAccount = null;
        systemConfig = null;
        Ext.create('MyApp.view.executeView', {fullscreen: true});
    }

});
