/*
 * File: app/controller/loginController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.loginController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mobilePhone: '#loginFormMobilePhoneID',
            email: '#loginFormEmailID',
            loginForm: '#LoginFormID',
            executeView: '#executeViewID'
        },

        control: {
            "#loginFormLoginWayID": {
                change: 'onLoginWayIDChange'
            },
            "button[itemId=loginLoginBtn]": {
                tap: 'onLoginLoginBtnTap'
            },
            "button[itemId=loginSettingBtn]": {
                tap: 'onSettingButtonTap'
            }
        }
    },

    onLoginWayIDChange: function(selectfield, newValue, oldValue, eOpts) {
        if (newValue == 'mobilePhone') {
            this.getMobilePhone().setHidden(false);
            this.getEmail().setHidden(true);
        } else {
            this.getMobilePhone().setHidden(true);
            this.getEmail().setHidden(false);
        }

    },

    onLoginLoginBtnTap: function(button, e, eOpts) {
        var values = this.getLoginForm().getValues();

        var username = null;
        if (values.loginWay == 'mobilePhone')
        username = values.mobilePhone;
        else
        username = values.email;

        var password = values.passwd;

        this.successLogin("http://localhost/ecshop/mobile/mobileService.php", username,password);

        if (loginAccount == null)
        alert("用户名/密码错误，请重新输入！");
        else
        this.getExecuteView().pop();



    },

    onSettingButtonTap: function(button, e, eOpts) {
        var settingForm = Ext.create('MyApp.view.settingForm');
        settingForm.setRecord(MyApp.systemConfig);
        this.getExecuteView().push(settingForm);
    },

    successLogin: function(url,username,password) {
        var servicePara = {
            InterfaceName: 'Login',
            SN:            '00000000001',
            DATA_LAST_UPDATE_DATETIME:  '20120101',
            USER_NAME:      username,
            USER_PWD:            password
        };

        var executeView = this.getExecuteView();
        loginSuccess = function(response) {
            //登录验证成功

            console.log("response:", response.responseText);
            if (response.responseText) {
                var retValue = Ext.decode(response.responseText);

                console.log(retValue);
                if (retValue.success == true) {
                    //将用户状态记录到全局帐户变量中保存
                    loginAccount = retValue;

                    console.log("successLogin: Login Account", loginAccount);
                }

                return;

            } else {
                alert("服务器错误！");
            }

        };

        this.getApplication().getController('webServiceController').service(servicePara, loginSuccess);
    }

});