/*
 * File: app/controller/orderController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.orderController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            executeView: '#executeViewID'
        },

        control: {
            "button[ItemId=btnBuyGoods]": {
                tap: 'onBtnBuyGoodsTap'
            }
        }
    },

    onBtnBuyGoodsTap: function(button, e, eOpts) {
        console.log("enter continue buy...");
        this.getExecuteView().pop();

        //this.getApplication().getController('orderController').displayShoppingCartView();
        var proListFrm = Ext.create('MyApp.view.productView');
        this.getExecuteView().push(proListFrm);
    },

    displayShoppingCartView: function() {
        var frm = Ext.create('MyApp.view.shoppingCartView');
        this.getExecuteView().push(frm);

    }

});