/*
 * File: app/controller/webServiceController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.webServiceController', {
    extend: 'Ext.app.Controller',

    config: {
    },

    service: function(params,callbackFunc) {
        // Add default params
        //params.format = 'json';

        console.log(params.url);

        var urlStr = systemConfig.System_ProxyRootURL;
        if (params.url != null) {
            urlStr = params.url;
        }

        console.log(urlStr);

        // convert from milisecond to second
        var timeout = systemConfig.System_ProxyTimeout * 1000;
        if(params.timeout !== null)
        timeout = params.timeout * 1000;

        //var callbackKey = 'callback' + Ext.id(null, '_');
        try{
            var mask = null;
            if(params.mask != null) 
            mask = params.mask;

            /* Todo 处理
            jsonPTimeout(mask, timeout, function(){
            Ext.Msg.alert('Server', 'JSONP: Request Timeout!');
            });
            */

            // Remove some params
            params.mask = '';

            Ext.Ajax.request({
                withCredentials: true,
                disableCaching: false,
                useDefaultXhrHeader: false,
                url: urlStr,
                params: params,
                success:  callbackFunc

            });
        }catch(ex){
            //removeAllXmask();
            console.log('Ext.util.JSONP.request throw an exception:');
            console.log(ex);
        }	
    }

});